fix lint error

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,15 +1,18 @@
 #!/bin/sh
 
 
-STAGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".py$")
-
 PASS=true
+
 # Would be cool if we could format and add the changes to the commit.
-#if [[ $STAGED_PY_FILES ]]; then
-#  # Run Black on project
-#  printf "\t\033[32mFormatting Project with Black\033[0m\n"
-#  black ./
-#fi
+black ./ --check
+if [[ "$?" == 0 ]]; then
+  printf "\t\033[32mformmating Passed: $FILE\033[0m\n"
+else
+  printf "\t\033[41formatting Failed: $FILE\033[0m\n"
+  PASS=false
+fi
+
+STAGED_PY_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "src" | grep ".py$")
 
 for FILE in $STAGED_PY_FILES
 do
@@ -18,14 +21,6 @@ do
     printf "\t\033[32mpylint Passed: $FILE\033[0m\n"
   else
     printf "\t\033[41mpylint Failed: $FILE\033[0m\n"
-    PASS=false
-  fi
-
-  black "$FILE" --check
-  if [[ "$?" == 0 ]]; then
-    printf "\t\033[32mformmating Passed: $FILE\033[0m\n"
-  else
-    printf "\t\033[41formatting Failed: $FILE\033[0m\n"
     PASS=false
   fi
 
